version: '2'

services:
    phabricator:
        build: . 
        container_name: "phabricator"
        environment:
            - VIRTUAL_HOST=phabricator.lan,cdn.phabricator.lan
            - MYSQL_HOST=db
            - MYSQL_USER=phabricator
            - MYSQL_PASSWORD=phabricator
            - MYSQL_PORT=3306
            - BASE_URI=http://phabricator.lan
            - CDN_URI=http://cdn.phabricator.lan
            - LOCAL_PATH=/var/www/phabricator/store
            - FORCE_HTTPS=false
        volumes:
            - ./data/repos:/var/repo
            - ./data/store:/var/www/phabricator/store  
        ports:
            - "10780:80"
            - "10743:443"
        tty: true

networks:
    default:
        external:
            name: proxied
